### ISSUE TITLE
Can you please add hex color support and plugin is not working on purpur version 1.20.4

### ISSUE THREAD

**Issue by ThomasDeStrooper** [jaqobb-mc/message-editor#42]
Can you please add support for hex colors. also Plugin is not working on purpur 1.20.4 it says this: - [wo 19:59:28 ERROR Minecraft] Could not pass event InventoryClickEvent to MessageEditor v2.5.5
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
    at message-editor-2.5.5-all.jar//dev.jaqobb.message_editor.listener.player.PlayerInventoryClickListener.onPlayerInventoryClick(PlayerInventoryClickListener.java:43)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1441.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123)
    at net.minecraft.server.Mine

**Comment by realistc** [comment]
not working*
